### ISSUE TITLE
Suggestions for FutureBB

### ISSUE THREAD

**Issue by axisdos** [futuresight/futurebb#81]
Hey guys, I'm currently testing out this forum software and I'm in love with it simplistic. However, some features needed to be add.

SEO Features:
1. SEO Friendly URL (Done)
2. Auto generate meta description based on first post excerpt (NOT DONE)

Post Editor:
The current post editor is too simple. I tried to implemented CKEditor (http://ckeditor.com/) and TinyMCE (http://www.tinymce.com/) but failed at it because I'm not really good at developing/coding.

Better Styling:
I love the simple default style, however, it's not responsive. It would be awesome if you could make the style fixed width and add responsiveness into it. Thanks!

**Comment by jacob-g** [comment]
Meta tags: https://github.com/futuresight/futurebb/issues/82
Editor: https://github.com/futuresight/futurebb/issues/83 (it will be an extension)
Styling: What exactly do you mean by "responsive"? We try to keep JS to a minimum in order to make the software as compatible as possible. However, we will make a fixed width add-on template (https://github.com/futuresight/futurebb/issues/84)

**Comment by axisdos** [comment]
Hey, by responsive I mean like the template will work great on mobile devices (mobile friendly). The current default template isn't responsive at all. 

When will you be able to make an extension for Post Editor and Template?

**Comment by jacob-g** [comment]
Sorry for the late reply, I didn't get a notification.

I will add a mobile style set to Version 1.3 (issue #86)

The extensions usually are developed after the core, so unfortunately probably not until I finish version 1.3.
